### ISSUE TITLE
Tomcat pack update blog post

### ISSUE THREAD

**Issue by mosabua** [oneops/oneops.github.io#90]
Work with @khushbulohia, @schwankl and @bbourqu

**Comment by mosabua** [comment]
As part of that I might introduce a section on the site about different packs and a specific page (or section of pages) about the tomcat pack.

**Comment by bbourqu** [comment]
# Announcing Tomcat 7.0.75 for immediate use in the Tomcat v1 pack

This release provides the following changes:

- artifact component is now propagated to tomcat so that upgrades will redeploy artifact
- 75 has been added to the drop down for the build version mitigating [CVE-2016-8745](http://mail-archives.apache.org/mod_mbox/tomcat-announce/201701.mbox/%3C04ead0cb-c989-1386-0fd1-a51ef80f7b57%40apache.org%3E

**Comment by mosabua** [comment]
What about Tomcat 8 and 8.5 ? Do we have packs for those that are updated as well?

**Comment by mosabua** [comment]
See https://github.com/oneops/circuit-oneops-1/pull/681/

**Comment by bbourqu** [comment]
8 is not an update branch we keep up with only 8.5.x.  Those will be updated as well after this update.  Its only me for the moment and this pack is a very widely used pack so changes have to be done methodically.

**Comment by mosabua** [comment]
See https://github.com/oneops/oneops.github.io/pull/92

**Comment by mosabua** [comment]
Published.
